version: '3.8'

services:
  spring:
    container_name: spring-app
    image: spring-app
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./config/application.properties:/app/src/main/resources/application.properties

  postgres:
    image: postgres:16
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: angela
      POSTGRES_DB: kiii
    restart: unless-stopped
