apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-springboot-configmap
  namespace: kiii-project
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://pg-service.kiii-project.svc.cluster.local:5432/kiii
    spring.datasource.username=postgres
    spring.datasource.password=postgres
    spring.datasource.hikari.connectionTimeout=20000
    spring.datasource.hikari.maximumPoolSize=5
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-springboot-deployment
  namespace: kiii-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kiii-springboot-pod
  template:
    metadata:
      labels:
        app: kiii-springboot-pod
    spec:
      containers:
        - name: kiii-springboot
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
          image: angelaivanova27/spring-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kiii-springboot-configmap-volume
              mountPath: /app/config/application.properties
      volumes:
        - name: kiii-springboot-configmap-volume
          configMap:
            name: kiii-springboot-configmap